defmodule Kapelle.Orchestrator.PersistenceTest do
  use Kapelle.DataCase, async: true

  alias Kapelle.Evaluator.Verdict
  alias Kapelle.Executor.Result
  alias Kapelle.Orchestrator.Persistence
  alias Kapelle.Orchestrator.Records.Decision, as: DecisionRecord
  alias Kapelle.Orchestrator.Records.Run
  alias Kapelle.Orchestrator.Records.RunTask
  alias Kapelle.Orchestrator.Records.Verdict, as: VerdictRecord
  alias Kapelle.Router.Decision

  describe "run_attrs/1" do
    test "builds Records.Run attrs from a submitted task map" do
      task = %{id: "task-1", type: :code_gen}

      assert Persistence.run_attrs(task) == %{task_id: "task-1", status: "completed"}
    end

    test "does not silently drop the task_id or status keys" do
      attrs = Persistence.run_attrs(%{id: "task-2", type: :summarize})

      assert Map.has_key?(attrs, :task_id)
      assert Map.has_key?(attrs, :status)
      assert map_size(attrs) == 2
    end
  end

  describe "run_task_attrs/2" do
    test "builds Records.RunTask attrs from an Executor.Result, linked to run_id" do
      result =
        Result.new!(%{
          task_id: "task-1",
          status: :pass,
          output: %{stdout: "ok"},
          duration_ms: 1234,
          artifacts: [%{path: "report.json"}]
        })

      assert Persistence.run_task_attrs("run-1", result) == %{
               run_id: "run-1",
               task_id: "task-1",
               status: "pass",
               output: %{stdout: "ok"},
               duration_ms: 1234,
               artifacts: [%{path: "report.json"}]
             }
    end

    test "preserves output, artifacts, and duration_ms verbatim (no silent drop)" do
      result =
        Result.new!(%{
          task_id: "task-1",
          status: :fail,
          output: %{"nested" => %{"value" => 1}},
          duration_ms: 42,
          artifacts: [%{"path" => "a.txt"}, %{"path" => "b.txt"}]
        })

      attrs = Persistence.run_task_attrs("run-1", result)

      assert attrs.output == result.output
      assert attrs.artifacts == result.artifacts
      assert attrs.duration_ms == result.duration_ms
    end
  end

  describe "decision_attrs/2" do
    test "builds Records.Decision attrs from a Router.Decision, linked to run_task_id" do
      decision =
        Decision.new!(%{
          decision_id: "dec-1",
          task_id: "task-1",
          target: %{provider: "anthropic", model: "claude-sonnet-5"},
          decided_at: ~U[2026-08-04 12:00:00Z],
          features: %{temperature: 0.2}
        })

      assert Persistence.decision_attrs("run-task-1", decision) == %{
               id: "dec-1",
               run_task_id: "run-task-1",
               task_id: "task-1",
               target: %{provider: "anthropic", model: "claude-sonnet-5"},
               features: %{temperature: 0.2},
               decided_at: ~U[2026-08-04 12:00:00Z]
             }
    end

    test "sets id to decision.decision_id, not an autogenerated value" do
      decision =
        Decision.new!(%{
          decision_id: "dec-2",
          task_id: "task-1",
          target: %{provider: "anthropic", model: "claude-sonnet-5"},
          decided_at: ~U[2026-08-04 12:00:00Z]
        })

      attrs = Persistence.decision_attrs("run-task-1", decision)

      assert attrs.id == decision.decision_id
    end
  end

  describe "verdict_attrs/2" do
    test "builds Records.Verdict attrs from an Evaluator.Verdict, linked to decision_id" do
      verdict =
        Verdict.new!(%{
          decision_id: "dec-1",
          task_id: "task-1",
          total_score: 0.75,
          score_components: %{status_match: 1.0, latency: -0.25}
        })

      assert Persistence.verdict_attrs("dec-1", verdict) == %{
               decision_id: "dec-1",
               task_id: "task-1",
               total_score: 0.75,
               score_components: %{status_match: 1.0, latency: -0.25}
             }
    end

    test "never drops score_components, matching the contract struct's invariant" do
      verdict =
        Verdict.new!(%{
          decision_id: "dec-1",
          task_id: "task-1",
          total_score: 1.0,
          score_components: %{status_match: 1.0}
        })

      attrs = Persistence.verdict_attrs("dec-1", verdict)

      assert attrs.score_components == %{status_match: 1.0}
      refute attrs.score_components == %{}
    end

    test "preserves an empty score_components map instead of dropping the key" do
      verdict =
        Verdict.new!(%{
          decision_id: "dec-1",
          task_id: "task-1",
          total_score: 0.0,
          score_components: %{}
        })

      attrs = Persistence.verdict_attrs("dec-1", verdict)

      assert Map.has_key?(attrs, :score_components)
      assert attrs.score_components == %{}
    end
  end

  describe "record_run/4" do
    setup do
      task = %{id: "task-1", type: :code_gen}

      decision =
        Decision.new!(%{
          decision_id: Ecto.UUID.generate(),
          task_id: "task-1",
          target: %{provider: "anthropic", model: "claude-sonnet-5"},
          decided_at: DateTime.utc_now(),
          features: %{"temperature" => 0.2}
        })

      result =
        Result.new!(%{
          task_id: "task-1",
          status: :pass,
          output: %{
            "stdout" => "ok",
            "nested" => %{"exit_code" => 0, "warnings" => []}
          },
          duration_ms: 1234,
          artifacts: [
            %{"path" => "report.json", "size_bytes" => 512},
            %{"path" => "log.txt", "size_bytes" => 0}
          ]
        })

      verdict =
        Verdict.new!(%{
          decision_id: decision.decision_id,
          task_id: "task-1",
          total_score: 0.825,
          score_components: %{
            "status_match" => 1.0,
            "latency" => -0.175,
            "details" => %{"rubric" => "v2"}
          }
        })

      %{task: task, decision: decision, result: result, verdict: verdict}
    end

    test "inserts run, run_task, decision, and verdict rows linked by FK", %{
      task: task,
      decision: decision,
      result: result,
      verdict: verdict
    } do
      assert {:ok, %{run: run, run_task: run_task, decision: decision_row, verdict: verdict_row}} =
               Persistence.record_run(task, decision, result, verdict)

      assert %Run{} = run
      assert %RunTask{} = run_task
      assert %DecisionRecord{} = decision_row
      assert %VerdictRecord{} = verdict_row

      assert run_task.run_id == run.id
      assert decision_row.run_task_id == run_task.id
      assert decision_row.id == decision.decision_id
      assert verdict_row.decision_id == decision_row.id

      assert Repo.aggregate(Run, :count, :id) == 1
      assert Repo.aggregate(RunTask, :count, :id) == 1
      assert Repo.aggregate(DecisionRecord, :count, :id) == 1
      assert Repo.aggregate(VerdictRecord, :count, :id) == 1
    end

    test "round-trips score_components, artifacts, and output losslessly through the DB", %{
      task: task,
      decision: decision,
      result: result,
      verdict: verdict
    } do
      assert {:ok, %{run: run, run_task: run_task, decision: decision_row, verdict: verdict_row}} =
               Persistence.record_run(task, decision, result, verdict)

      reloaded_run = Repo.get!(Run, run.id)
      reloaded_run_task = Repo.get!(RunTask, run_task.id)
      reloaded_decision = Repo.get!(DecisionRecord, decision_row.id)
      reloaded_verdict = Repo.get!(VerdictRecord, verdict_row.id)

      assert reloaded_run.task_id == task.id
      assert reloaded_run.status == "completed"

      assert reloaded_run_task.status == "pass"
      assert reloaded_run_task.duration_ms == 1234
      assert reloaded_run_task.output == result.output
      assert reloaded_run_task.artifacts == result.artifacts

      assert reloaded_decision.target == %{
               "provider" => "anthropic",
               "model" => "claude-sonnet-5"
             }

      assert reloaded_decision.features == decision.features
      assert reloaded_decision.decided_at == decision.decided_at

      assert reloaded_verdict.total_score == verdict.total_score
      assert reloaded_verdict.score_components == verdict.score_components
    end

    test "rolls back all four inserts when a later step fails", %{
      task: task,
      decision: decision,
      result: result,
      verdict: verdict
    } do
      invalid_decision = %{decision | target: "not-a-map"}

      assert {:error, {:decision, changeset}} =
               Persistence.record_run(task, invalid_decision, result, verdict)

      assert %Ecto.Changeset{valid?: false} = changeset

      assert Repo.aggregate(Run, :count, :id) == 0
      assert Repo.aggregate(RunTask, :count, :id) == 0
      assert Repo.aggregate(DecisionRecord, :count, :id) == 0
      assert Repo.aggregate(VerdictRecord, :count, :id) == 0
    end

    test "rolls back the run insert when the run_task step fails", %{
      task: task,
      decision: decision,
      verdict: verdict
    } do
      invalid_result = %{
        Result.new!(%{
          task_id: "task-1",
          status: :pass,
          output: %{stdout: "ok"},
          duration_ms: 1234,
          artifacts: [%{path: "report.json"}]
        })
        | task_id: nil
      }

      assert {:error, {:run_task, changeset}} =
               Persistence.record_run(task, decision, invalid_result, verdict)

      assert %Ecto.Changeset{valid?: false} = changeset

      assert Repo.aggregate(Run, :count, :id) == 0
      assert Repo.aggregate(RunTask, :count, :id) == 0
    end

    test "rejects a verdict whose decision_id doesn't match the decision, without touching the DB",
         %{task: task, decision: decision, result: result} do
      mismatched_verdict =
        Verdict.new!(%{
          decision_id: Ecto.UUID.generate(),
          task_id: "task-1",
          total_score: 1.0,
          score_components: %{status_match: 1.0}
        })

      assert Persistence.record_run(task, decision, result, mismatched_verdict) ==
               {:error, :verdict_decision_mismatch}

      assert Repo.aggregate(Run, :count, :id) == 0
      assert Repo.aggregate(RunTask, :count, :id) == 0
      assert Repo.aggregate(DecisionRecord, :count, :id) == 0
      assert Repo.aggregate(VerdictRecord, :count, :id) == 0
    end

    test "rolls back run, run_task, and decision when a duplicate decision_id conflicts", %{
      task: task,
      decision: decision,
      result: result,
      verdict: verdict
    } do
      assert {:ok, _} = Persistence.record_run(task, decision, result, verdict)

      assert {:error, {:decision, changeset}} =
               Persistence.record_run(task, decision, result, verdict)

      assert %Ecto.Changeset{valid?: false} = changeset

      assert Repo.aggregate(Run, :count, :id) == 1
      assert Repo.aggregate(RunTask, :count, :id) == 1
      assert Repo.aggregate(DecisionRecord, :count, :id) == 1
      assert Repo.aggregate(VerdictRecord, :count, :id) == 1
    end
  end
end
