defmodule Kapelle.Orchestrator.PersistenceTest do
  use ExUnit.Case, async: true

  alias Kapelle.Evaluator.Verdict
  alias Kapelle.Executor.Result
  alias Kapelle.Orchestrator.Persistence
  alias Kapelle.Router.Decision

  describe "run_attrs/1" do
    test "builds Records.Run attrs from a submitted task map" do
      task = %{id: "task-1", type: :code_gen}

      assert Persistence.run_attrs(task) == %{task_id: "task-1", status: "completed"}
    end

    test "does not silently drop the task_id or status keys" do
      attrs = Persistence.run_attrs(%{id: "task-2", type: :summarize})

      assert Map.has_key?(attrs, :task_id)
      assert Map.has_key?(attrs, :status)
      assert map_size(attrs) == 2
    end
  end

  describe "run_task_attrs/2" do
    test "builds Records.RunTask attrs from an Executor.Result, linked to run_id" do
      result =
        Result.new!(%{
          task_id: "task-1",
          status: :pass,
          output: %{stdout: "ok"},
          duration_ms: 1234,
          artifacts: [%{path: "report.json"}]
        })

      assert Persistence.run_task_attrs("run-1", result) == %{
               run_id: "run-1",
               task_id: "task-1",
               status: "pass",
               output: %{stdout: "ok"},
               duration_ms: 1234,
               artifacts: [%{path: "report.json"}]
             }
    end

    test "preserves output, artifacts, and duration_ms verbatim (no silent drop)" do
      result =
        Result.new!(%{
          task_id: "task-1",
          status: :fail,
          output: %{"nested" => %{"value" => 1}},
          duration_ms: 42,
          artifacts: [%{"path" => "a.txt"}, %{"path" => "b.txt"}]
        })

      attrs = Persistence.run_task_attrs("run-1", result)

      assert attrs.output == result.output
      assert attrs.artifacts == result.artifacts
      assert attrs.duration_ms == result.duration_ms
    end
  end

  describe "decision_attrs/2" do
    test "builds Records.Decision attrs from a Router.Decision, linked to run_task_id" do
      decision =
        Decision.new!(%{
          decision_id: "dec-1",
          task_id: "task-1",
          target: %{provider: "anthropic", model: "claude-sonnet-5"},
          decided_at: ~U[2026-08-04 12:00:00Z],
          features: %{temperature: 0.2}
        })

      assert Persistence.decision_attrs("run-task-1", decision) == %{
               id: "dec-1",
               run_task_id: "run-task-1",
               task_id: "task-1",
               target: %{provider: "anthropic", model: "claude-sonnet-5"},
               features: %{temperature: 0.2},
               decided_at: ~U[2026-08-04 12:00:00Z]
             }
    end

    test "sets id to decision.decision_id, not an autogenerated value" do
      decision =
        Decision.new!(%{
          decision_id: "dec-2",
          task_id: "task-1",
          target: %{provider: "anthropic", model: "claude-sonnet-5"},
          decided_at: ~U[2026-08-04 12:00:00Z]
        })

      attrs = Persistence.decision_attrs("run-task-1", decision)

      assert attrs.id == decision.decision_id
    end
  end

  describe "verdict_attrs/2" do
    test "builds Records.Verdict attrs from an Evaluator.Verdict, linked to decision_id" do
      verdict =
        Verdict.new!(%{
          decision_id: "dec-1",
          task_id: "task-1",
          total_score: 0.75,
          score_components: %{status_match: 1.0, latency: -0.25}
        })

      assert Persistence.verdict_attrs("dec-1", verdict) == %{
               decision_id: "dec-1",
               task_id: "task-1",
               total_score: 0.75,
               score_components: %{status_match: 1.0, latency: -0.25}
             }
    end

    test "never drops score_components, matching the contract struct's invariant" do
      verdict =
        Verdict.new!(%{
          decision_id: "dec-1",
          task_id: "task-1",
          total_score: 1.0,
          score_components: %{status_match: 1.0}
        })

      attrs = Persistence.verdict_attrs("dec-1", verdict)

      assert attrs.score_components == %{status_match: 1.0}
      refute attrs.score_components == %{}
    end

    test "preserves an empty score_components map instead of dropping the key" do
      verdict =
        Verdict.new!(%{
          decision_id: "dec-1",
          task_id: "task-1",
          total_score: 0.0,
          score_components: %{}
        })

      attrs = Persistence.verdict_attrs("dec-1", verdict)

      assert Map.has_key?(attrs, :score_components)
      assert attrs.score_components == %{}
    end
  end
end
