defmodule Kapelle.Orchestrator.Records.Decision do
  @moduledoc """
  Ecto schema for the `decisions` table.

  One row per `Kapelle.Router.Decision` routed for a `run_task`. The
  primary key is **not** autogenerated — it is set to the contract
  struct's `decision_id` verbatim so `verdicts.decision_id` can
  reference it without a redundant mirror column.
  """

  use Ecto.Schema
  import Ecto.Changeset

  alias Kapelle.Orchestrator.Records.RunTask
  alias Kapelle.Orchestrator.Records.Verdict

  @primary_key {:id, :binary_id, autogenerate: false}
  @foreign_key_type :binary_id

  schema "decisions" do
    field :task_id, :string
    field :target, :map
    field :features, :map, default: %{}
    field :decided_at, :utc_datetime_usec

    belongs_to :run_task, RunTask
    has_one :verdict, Verdict

    timestamps()
  end

  @type t :: %__MODULE__{
          id: Ecto.UUID.t() | nil,
          task_id: String.t() | nil,
          target: map() | nil,
          features: map(),
          decided_at: DateTime.t() | nil,
          run_task_id: Ecto.UUID.t() | nil,
          run_task: RunTask.t() | Ecto.Association.NotLoaded.t(),
          verdict: Verdict.t() | Ecto.Association.NotLoaded.t() | nil,
          inserted_at: DateTime.t() | nil,
          updated_at: DateTime.t() | nil
        }

  @doc """
  Builds a changeset for `decision`, casting the `decisions` fields
  (including the caller-supplied `:id`, since it is not autogenerated)
  and requiring `id`, `run_task_id`, `task_id`, and `decided_at`,
  matching the table's NOT NULL columns.
  """
  @spec changeset(t(), map()) :: Ecto.Changeset.t()
  def changeset(decision, attrs) do
    decision
    |> cast(attrs, [:id, :run_task_id, :task_id, :target, :features, :decided_at])
    |> validate_required([:id, :run_task_id, :task_id, :target, :decided_at])
    |> unique_constraint(:id, name: :decisions_pkey)
    |> unique_constraint(:run_task_id)
    |> foreign_key_constraint(:run_task_id)
  end
end
