#!/usr/bin/env bash
# Generate a golden scenario's evidence from the PINNED reference runner.
# Usage: scripts/gen_golden.sh <path-to-impresario-checkout> [scenario]
#        scenario: happy (default) | needs_human | resume
# Explicit, reviewable golden update (owner's S2 preamble, item 6):
# never run automatically, never on test failure.
#
# Parameterised by scenario rather than hard-wired to happy: the needs-human
# oracle has to exist *before* the code that is judged against it, or the
# project would be checking itself against an expectation written after its
# own result.
set -euo pipefail

IMPRESARIO="${1:?path to impresario checkout}"
SCENARIO="${2:-happy}"
case "$SCENARIO" in
  happy|needs_human|resume) ;;
  *) echo "unknown scenario '$SCENARIO' (expected: happy | needs_human | resume)" >&2; exit 2 ;;
esac
# Single producer pin, same as priv/contracts/impresario (anti-mix across
# vendor and goldens). The resume scenario REQUIRES this pin or later: the
# producer's resume authors a loop-resume-decision only from 8082e53 on.
COMMIT="8082e53b743169137f9e8c72c279043c7166ab03"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/test/support/fixtures/golden/$SCENARIO"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

git -C "$IMPRESARIO" archive "$COMMIT" | tar -x -C "$TMP"

python3 -m venv "$TMP/venv"
"$TMP/venv/bin/pip" -q install -e "$TMP" >/dev/null

# The producer's own test fixtures define the deterministic happy-path agent;
# gen_golden_run.py ports tests/test_loop.py's HAPPY_SCRIPT (init_loop +
# run_loop via ScriptedAgent) rather than importing it, since importing the
# producer's test module would pull in its dev-only pytest dependency, which
# this editable install (main dependencies only) does not provision.
GEN_RUN_ARGV=("$TMP" "$TMP/ws" "$SCENARIO")
"$TMP/venv/bin/python" "$ROOT/scripts/gen_golden_run.py" "${GEN_RUN_ARGV[@]}"

rm -rf "$OUT" && mkdir -p "$OUT"
cp "$TMP/ws/trace.jsonl" "$OUT/raw-trace.jsonl"
mkdir -p "$OUT/workspace" && cp -R "$TMP/ws/." "$OUT/workspace/"

# normalized.json is generated by the app itself, not hand-written: the
# committed golden must always be exactly what Kapelle.Product.Oracle.Normalizer
# produces from the committed raw-trace.jsonl, never a stand-in built by a
# test helper.
#
# Compile first, discarding Mix's "Compiling N files"/"Generated kapelle app"
# chatter, so the `mix run --no-compile -e` calls below emit ONLY what the
# script itself prints on stdout.
(cd "$ROOT" && mix compile >/dev/null)

NORMALIZER_VERSION="$(
  cd "$ROOT" && mix run --no-compile -e 'IO.write(Kapelle.Product.Oracle.Normalizer.version())'
)"

(cd "$ROOT" && mix run --no-compile -e '
  raw =
    File.stream!("'"$OUT"'/raw-trace.jsonl")
    |> Enum.map(&Jason.decode!/1)

  normalized = Jason.encode!(Kapelle.Product.Oracle.Normalizer.normalize(raw), pretty: true)
  File.write!("'"$OUT"'/normalized.json", normalized <> "\n")
')

{
  echo "scenario: $SCENARIO"
  echo "producer: impresario@$COMMIT (full tree via git archive)"
  echo "generated: $(date +%Y-%m-%d)"
  echo "generator: scripts/gen_golden.sh + scripts/gen_golden_run.py"
  echo "generator argv: gen_golden_run.py ${GEN_RUN_ARGV[*]}"
  echo "generator sha256: $(shasum -a 256 "$ROOT/scripts/gen_golden.sh" | cut -d' ' -f1)  scripts/gen_golden.sh"
  echo "generator sha256: $(shasum -a 256 "$ROOT/scripts/gen_golden_run.py" | cut -d' ' -f1)  scripts/gen_golden_run.py"
  echo "normalizer: lib/kapelle/product/oracle/normalizer.ex version() = $NORMALIZER_VERSION"
  (cd "$OUT" && find . -type f ! -name PROVENANCE | LC_ALL=C sort | while read -r f; do
    echo "sha256 $f: $(shasum -a 256 "$f" | cut -d' ' -f1)"
  done)
} > "$OUT/PROVENANCE"

echo "wrote $OUT"
